// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package registers_pkg;

    localparam REGISTERS_DATA_WIDTH = 32;
    localparam REGISTERS_MIN_ADDR_WIDTH = 32;
    localparam REGISTERS_SIZE = 'h2c;

    typedef struct {
        logic [10:0] next;
    } registers__data_packet_buffer_write_ptr_reg__WPTR__in_t;

    typedef struct {
        registers__data_packet_buffer_write_ptr_reg__WPTR__in_t WPTR;
    } registers__data_packet_buffer_write_ptr_reg__in_t;

    typedef struct {
        logic next;
    } registers__data_packet_buffer_status_reg__EMPTY__in_t;

    typedef struct {
        logic next;
    } registers__data_packet_buffer_status_reg__FULL__in_t;

    typedef struct {
        registers__data_packet_buffer_status_reg__EMPTY__in_t EMPTY;
        registers__data_packet_buffer_status_reg__FULL__in_t FULL;
    } registers__data_packet_buffer_status_reg__in_t;

    typedef struct {
        registers__data_packet_buffer_write_ptr_reg__in_t WRITE_PTR;
        registers__data_packet_buffer_status_reg__in_t STATUS;
    } registers__in_t;

    typedef struct {
        logic [20:0] value;
    } registers__data_packet_buffer_write_ptr_reg__RESERVED__out_t;

    typedef struct {
        registers__data_packet_buffer_write_ptr_reg__RESERVED__out_t RESERVED;
    } registers__data_packet_buffer_write_ptr_reg__out_t;

    typedef struct {
        logic [10:0] value;
    } registers__data_packet_buffer_read_ptr_reg__RPTR__out_t;

    typedef struct {
        logic [20:0] value;
    } registers__data_packet_buffer_read_ptr_reg__RESERVED__out_t;

    typedef struct {
        registers__data_packet_buffer_read_ptr_reg__RPTR__out_t RPTR;
        registers__data_packet_buffer_read_ptr_reg__RESERVED__out_t RESERVED;
    } registers__data_packet_buffer_read_ptr_reg__out_t;

    typedef struct {
        logic [29:0] value;
    } registers__data_packet_buffer_status_reg__RESERVED__out_t;

    typedef struct {
        registers__data_packet_buffer_status_reg__RESERVED__out_t RESERVED;
    } registers__data_packet_buffer_status_reg__out_t;

    typedef struct {
        logic [31:0] value;
    } registers__crash_detection_speed_threshold_reg__THRESH__out_t;

    typedef struct {
        registers__crash_detection_speed_threshold_reg__THRESH__out_t THRESH;
    } registers__crash_detection_speed_threshold_reg__out_t;

    typedef struct {
        logic [31:0] value;
    } registers__crash_detection_non_fatal_accel_threshold_reg__THRESH__out_t;

    typedef struct {
        registers__crash_detection_non_fatal_accel_threshold_reg__THRESH__out_t THRESH;
    } registers__crash_detection_non_fatal_accel_threshold_reg__out_t;

    typedef struct {
        logic [31:0] value;
    } registers__crash_detection_fatal_accel_threshold_reg__THRESH__out_t;

    typedef struct {
        registers__crash_detection_fatal_accel_threshold_reg__THRESH__out_t THRESH;
    } registers__crash_detection_fatal_accel_threshold_reg__out_t;

    typedef struct {
        logic [31:0] value;
    } registers__crash_detection_angular_speed_threshold_reg__THRESH__out_t;

    typedef struct {
        registers__crash_detection_angular_speed_threshold_reg__THRESH__out_t THRESH;
    } registers__crash_detection_angular_speed_threshold_reg__out_t;

    typedef struct {
        logic value;
    } registers__crash_detection_enable_reg__EN__out_t;

    typedef struct {
        logic [30:0] value;
    } registers__crash_detection_enable_reg__RESERVED__out_t;

    typedef struct {
        registers__crash_detection_enable_reg__EN__out_t EN;
        registers__crash_detection_enable_reg__RESERVED__out_t RESERVED;
    } registers__crash_detection_enable_reg__out_t;

    typedef struct {
        logic value;
    } registers__crash_detection_state_reset_reg__RST__out_t;

    typedef struct {
        logic [30:0] value;
    } registers__crash_detection_state_reset_reg__RESERVED__out_t;

    typedef struct {
        registers__crash_detection_state_reset_reg__RST__out_t RST;
        registers__crash_detection_state_reset_reg__RESERVED__out_t RESERVED;
    } registers__crash_detection_state_reset_reg__out_t;

    typedef struct {
        logic value;
    } registers__polling_module_en__EN__out_t;

    typedef struct {
        logic [30:0] value;
    } registers__polling_module_en__RESERVED__out_t;

    typedef struct {
        registers__polling_module_en__EN__out_t EN;
        registers__polling_module_en__RESERVED__out_t RESERVED;
    } registers__polling_module_en__out_t;

    typedef struct {
        logic value;
    } registers__data_packager_en__EN__out_t;

    typedef struct {
        logic [30:0] value;
    } registers__data_packager_en__RESERVED__out_t;

    typedef struct {
        registers__data_packager_en__EN__out_t EN;
        registers__data_packager_en__RESERVED__out_t RESERVED;
    } registers__data_packager_en__out_t;

    typedef struct {
        registers__data_packet_buffer_write_ptr_reg__out_t WRITE_PTR;
        registers__data_packet_buffer_read_ptr_reg__out_t READ_PTR;
        registers__data_packet_buffer_status_reg__out_t STATUS;
        registers__crash_detection_speed_threshold_reg__out_t CD_SPEED_THRESH;
        registers__crash_detection_non_fatal_accel_threshold_reg__out_t CD_NON_FATAL_ACCEL_THRESH;
        registers__crash_detection_fatal_accel_threshold_reg__out_t CD_FATAL_ACCEL_THRESH;
        registers__crash_detection_angular_speed_threshold_reg__out_t CD_ANGULAR_SPEED_THRESH;
        registers__crash_detection_enable_reg__out_t CD_EN;
        registers__crash_detection_state_reset_reg__out_t CD_STATE_RST;
        registers__polling_module_en__out_t POLLING_EN;
        registers__data_packager_en__out_t DATA_PACAKGER_EN;
    } registers__out_t;
endpackage
