// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module registers (
        input wire clk,
        input wire arst_n,

        output logic s_axil_awready,
        input wire s_axil_awvalid,
        input wire [31:0] s_axil_awaddr,
        input wire [2:0] s_axil_awprot,
        output logic s_axil_wready,
        input wire s_axil_wvalid,
        input wire [31:0] s_axil_wdata,
        input wire [3:0]s_axil_wstrb,
        input wire s_axil_bready,
        output logic s_axil_bvalid,
        output logic [1:0] s_axil_bresp,
        output logic s_axil_arready,
        input wire s_axil_arvalid,
        input wire [31:0] s_axil_araddr,
        input wire [2:0] s_axil_arprot,
        input wire s_axil_rready,
        output logic s_axil_rvalid,
        output logic [31:0] s_axil_rdata,
        output logic [1:0] s_axil_rresp,

        input registers_pkg::registers__in_t hwif_in,
        output registers_pkg::registers__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [31:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Max Outstanding Transactions: 2
    logic [1:0] axil_n_in_flight;
    logic axil_prev_was_rd;
    logic axil_arvalid;
    logic [31:0] axil_araddr;
    logic axil_ar_accept;
    logic axil_awvalid;
    logic [31:0] axil_awaddr;
    logic axil_wvalid;
    logic [31:0] axil_wdata;
    logic [3:0] axil_wstrb;
    logic axil_aw_accept;
    logic axil_resp_acked;

    // Transaction request acceptance
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            axil_prev_was_rd <= '0;
            axil_arvalid <= '0;
            axil_araddr <= '0;
            axil_awvalid <= '0;
            axil_awaddr <= '0;
            axil_wvalid <= '0;
            axil_wdata <= '0;
            axil_wstrb <= '0;
            axil_n_in_flight <= '0;
        end else begin
            // AR* acceptance register
            if(axil_ar_accept) begin
                axil_prev_was_rd <= '1;
                axil_arvalid <= '0;
            end
            if(s_axil_arvalid && s_axil_arready) begin
                axil_arvalid <= '1;
                axil_araddr <= s_axil_araddr;
            end

            // AW* & W* acceptance registers
            if(axil_aw_accept) begin
                axil_prev_was_rd <= '0;
                axil_awvalid <= '0;
                axil_wvalid <= '0;
            end
            if(s_axil_awvalid && s_axil_awready) begin
                axil_awvalid <= '1;
                axil_awaddr <= s_axil_awaddr;
            end
            if(s_axil_wvalid && s_axil_wready) begin
                axil_wvalid <= '1;
                axil_wdata <= s_axil_wdata;
                axil_wstrb <= s_axil_wstrb;
            end

            // Keep track of in-flight transactions
            if((axil_ar_accept || axil_aw_accept) && !axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight + 1'b1;
            end else if(!(axil_ar_accept || axil_aw_accept) && axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight - 1'b1;
            end
        end
    end

    always_comb begin
        s_axil_arready = (!axil_arvalid || axil_ar_accept);
        s_axil_awready = (!axil_awvalid || axil_aw_accept);
        s_axil_wready = (!axil_wvalid || axil_aw_accept);
    end

    // Request dispatch
    always_comb begin
        cpuif_wr_data = axil_wdata;
        for(int i=0; i<4; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{axil_wstrb[i]}};
        end
        cpuif_req = '0;
        cpuif_req_is_wr = '0;
        cpuif_addr = '0;
        axil_ar_accept = '0;
        axil_aw_accept = '0;

        if(axil_n_in_flight < 2'd2) begin
            // Can safely issue more transactions without overwhelming response buffer
            if(axil_arvalid && !axil_prev_was_rd) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[31:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end else if(axil_awvalid && axil_wvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '1;
                cpuif_addr = {axil_awaddr[31:2], 2'b0};
                if(!cpuif_req_stall_wr) axil_aw_accept = '1;
            end else if(axil_arvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[31:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end
        end
    end


    // AXI4-Lite Response Logic
    logic axil_resp_buffer_is_wr[2];
    logic axil_resp_buffer_err[2];
    logic [31:0] axil_resp_buffer_rdata[2];

    logic [1:0] axil_resp_wptr;
    logic [1:0] axil_resp_rptr;

    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            for(int i=0; i<2; i++) begin
                axil_resp_buffer_is_wr[i] <= '0;
                axil_resp_buffer_err[i] <= '0;
                axil_resp_buffer_rdata[i] <= '0;
            end
            axil_resp_wptr <= '0;
            axil_resp_rptr <= '0;
        end else begin
            // Store responses in buffer until AXI response channel accepts them
            if(cpuif_rd_ack || cpuif_wr_ack) begin
                if(cpuif_rd_ack) begin
                    axil_resp_buffer_is_wr[axil_resp_wptr[0:0]] <= '0;
                    axil_resp_buffer_err[axil_resp_wptr[0:0]] <= cpuif_rd_err;
                    axil_resp_buffer_rdata[axil_resp_wptr[0:0]] <= cpuif_rd_data;

                end else if(cpuif_wr_ack) begin
                    axil_resp_buffer_is_wr[axil_resp_wptr[0:0]] <= '1;
                    axil_resp_buffer_err[axil_resp_wptr[0:0]] <= cpuif_wr_err;
                end
                axil_resp_wptr <= axil_resp_wptr + 1'b1;
            end

            // Advance read pointer when acknowledged
            if(axil_resp_acked) begin
                axil_resp_rptr <= axil_resp_rptr + 1'b1;
            end
        end
    end

    always_comb begin
        axil_resp_acked = '0;
        s_axil_bvalid = '0;
        s_axil_rvalid = '0;
        if(axil_resp_rptr != axil_resp_wptr) begin
            if(axil_resp_buffer_is_wr[axil_resp_rptr[0:0]]) begin
                s_axil_bvalid = '1;
                if(s_axil_bready) axil_resp_acked = '1;
            end else begin
                s_axil_rvalid = '1;
                if(s_axil_rready) axil_resp_acked = '1;
            end
        end

        s_axil_rdata = axil_resp_buffer_rdata[axil_resp_rptr[0:0]];
        if(axil_resp_buffer_err[axil_resp_rptr[0:0]]) begin
            s_axil_bresp = 2'b10;
            s_axil_rresp = 2'b10;
        end else begin
            s_axil_bresp = 2'b00;
            s_axil_rresp = 2'b00;
        end
    end

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic WRITE_PTR;
        logic READ_PTR;
        logic STATUS;
        logic CD_SPEED_THRESH;
        logic CD_NON_FATAL_ACCEL_THRESH;
        logic CD_FATAL_ACCEL_THRESH;
        logic CD_ANGULAR_SPEED_THRESH;
        logic CD_EN;
        logic CD_STATE_RST;
        logic POLLING_EN;
        logic DATA_PACAKGER_EN;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [31:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.WRITE_PTR = cpuif_req_masked & (cpuif_addr == 32'h0);
        decoded_reg_strb.READ_PTR = cpuif_req_masked & (cpuif_addr == 32'h4);
        decoded_reg_strb.STATUS = cpuif_req_masked & (cpuif_addr == 32'h8);
        decoded_reg_strb.CD_SPEED_THRESH = cpuif_req_masked & (cpuif_addr == 32'hc);
        decoded_reg_strb.CD_NON_FATAL_ACCEL_THRESH = cpuif_req_masked & (cpuif_addr == 32'h10);
        decoded_reg_strb.CD_FATAL_ACCEL_THRESH = cpuif_req_masked & (cpuif_addr == 32'h14);
        decoded_reg_strb.CD_ANGULAR_SPEED_THRESH = cpuif_req_masked & (cpuif_addr == 32'h18);
        decoded_reg_strb.CD_EN = cpuif_req_masked & (cpuif_addr == 32'h1c);
        decoded_reg_strb.CD_STATE_RST = cpuif_req_masked & (cpuif_addr == 32'h20);
        decoded_reg_strb.POLLING_EN = cpuif_req_masked & (cpuif_addr == 32'h24);
        decoded_reg_strb.DATA_PACAKGER_EN = cpuif_req_masked & (cpuif_addr == 32'h28);
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [20:0] next;
                logic load_next;
            } RESERVED;
        } WRITE_PTR;
        struct {
            struct {
                logic [10:0] next;
                logic load_next;
            } RPTR;
            struct {
                logic [20:0] next;
                logic load_next;
            } RESERVED;
        } READ_PTR;
        struct {
            struct {
                logic [29:0] next;
                logic load_next;
            } RESERVED;
        } STATUS;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } THRESH;
        } CD_SPEED_THRESH;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } THRESH;
        } CD_NON_FATAL_ACCEL_THRESH;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } THRESH;
        } CD_FATAL_ACCEL_THRESH;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } THRESH;
        } CD_ANGULAR_SPEED_THRESH;
        struct {
            struct {
                logic next;
                logic load_next;
            } EN;
            struct {
                logic [30:0] next;
                logic load_next;
            } RESERVED;
        } CD_EN;
        struct {
            struct {
                logic next;
                logic load_next;
            } RST;
            struct {
                logic [30:0] next;
                logic load_next;
            } RESERVED;
        } CD_STATE_RST;
        struct {
            struct {
                logic next;
                logic load_next;
            } EN;
            struct {
                logic [30:0] next;
                logic load_next;
            } RESERVED;
        } POLLING_EN;
        struct {
            struct {
                logic next;
                logic load_next;
            } EN;
            struct {
                logic [30:0] next;
                logic load_next;
            } RESERVED;
        } DATA_PACAKGER_EN;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [20:0] value;
            } RESERVED;
        } WRITE_PTR;
        struct {
            struct {
                logic [10:0] value;
            } RPTR;
            struct {
                logic [20:0] value;
            } RESERVED;
        } READ_PTR;
        struct {
            struct {
                logic [29:0] value;
            } RESERVED;
        } STATUS;
        struct {
            struct {
                logic [31:0] value;
            } THRESH;
        } CD_SPEED_THRESH;
        struct {
            struct {
                logic [31:0] value;
            } THRESH;
        } CD_NON_FATAL_ACCEL_THRESH;
        struct {
            struct {
                logic [31:0] value;
            } THRESH;
        } CD_FATAL_ACCEL_THRESH;
        struct {
            struct {
                logic [31:0] value;
            } THRESH;
        } CD_ANGULAR_SPEED_THRESH;
        struct {
            struct {
                logic value;
            } EN;
            struct {
                logic [30:0] value;
            } RESERVED;
        } CD_EN;
        struct {
            struct {
                logic value;
            } RST;
            struct {
                logic [30:0] value;
            } RESERVED;
        } CD_STATE_RST;
        struct {
            struct {
                logic value;
            } EN;
            struct {
                logic [30:0] value;
            } RESERVED;
        } POLLING_EN;
        struct {
            struct {
                logic value;
            } EN;
            struct {
                logic [30:0] value;
            } RESERVED;
        } DATA_PACAKGER_EN;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: registers.WRITE_PTR.RESERVED
    always_comb begin
        automatic logic [20:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.WRITE_PTR.RESERVED.value;
        load_next_c = '0;
        if(decoded_reg_strb.WRITE_PTR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.WRITE_PTR.RESERVED.value & ~decoded_wr_biten[31:11]) | (decoded_wr_data[31:11] & decoded_wr_biten[31:11]);
            load_next_c = '1;
        end
        field_combo.WRITE_PTR.RESERVED.next = next_c;
        field_combo.WRITE_PTR.RESERVED.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.WRITE_PTR.RESERVED.value <= 21'h0;
        end else begin
            if(field_combo.WRITE_PTR.RESERVED.load_next) begin
                field_storage.WRITE_PTR.RESERVED.value <= field_combo.WRITE_PTR.RESERVED.next;
            end
        end
    end
    assign hwif_out.WRITE_PTR.RESERVED.value = field_storage.WRITE_PTR.RESERVED.value;
    // Field: registers.READ_PTR.RPTR
    always_comb begin
        automatic logic [10:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.READ_PTR.RPTR.value;
        load_next_c = '0;
        if(decoded_reg_strb.READ_PTR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.READ_PTR.RPTR.value & ~decoded_wr_biten[10:0]) | (decoded_wr_data[10:0] & decoded_wr_biten[10:0]);
            load_next_c = '1;
        end
        field_combo.READ_PTR.RPTR.next = next_c;
        field_combo.READ_PTR.RPTR.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.READ_PTR.RPTR.value <= 11'h0;
        end else begin
            if(field_combo.READ_PTR.RPTR.load_next) begin
                field_storage.READ_PTR.RPTR.value <= field_combo.READ_PTR.RPTR.next;
            end
        end
    end
    assign hwif_out.READ_PTR.RPTR.value = field_storage.READ_PTR.RPTR.value;
    // Field: registers.READ_PTR.RESERVED
    always_comb begin
        automatic logic [20:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.READ_PTR.RESERVED.value;
        load_next_c = '0;
        if(decoded_reg_strb.READ_PTR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.READ_PTR.RESERVED.value & ~decoded_wr_biten[31:11]) | (decoded_wr_data[31:11] & decoded_wr_biten[31:11]);
            load_next_c = '1;
        end
        field_combo.READ_PTR.RESERVED.next = next_c;
        field_combo.READ_PTR.RESERVED.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.READ_PTR.RESERVED.value <= 21'h0;
        end else begin
            if(field_combo.READ_PTR.RESERVED.load_next) begin
                field_storage.READ_PTR.RESERVED.value <= field_combo.READ_PTR.RESERVED.next;
            end
        end
    end
    assign hwif_out.READ_PTR.RESERVED.value = field_storage.READ_PTR.RESERVED.value;
    // Field: registers.STATUS.RESERVED
    always_comb begin
        automatic logic [29:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.STATUS.RESERVED.value;
        load_next_c = '0;
        if(decoded_reg_strb.STATUS && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.STATUS.RESERVED.value & ~decoded_wr_biten[31:2]) | (decoded_wr_data[31:2] & decoded_wr_biten[31:2]);
            load_next_c = '1;
        end
        field_combo.STATUS.RESERVED.next = next_c;
        field_combo.STATUS.RESERVED.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.STATUS.RESERVED.value <= 30'h0;
        end else begin
            if(field_combo.STATUS.RESERVED.load_next) begin
                field_storage.STATUS.RESERVED.value <= field_combo.STATUS.RESERVED.next;
            end
        end
    end
    assign hwif_out.STATUS.RESERVED.value = field_storage.STATUS.RESERVED.value;
    // Field: registers.CD_SPEED_THRESH.THRESH
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CD_SPEED_THRESH.THRESH.value;
        load_next_c = '0;
        if(decoded_reg_strb.CD_SPEED_THRESH && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CD_SPEED_THRESH.THRESH.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CD_SPEED_THRESH.THRESH.next = next_c;
        field_combo.CD_SPEED_THRESH.THRESH.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.CD_SPEED_THRESH.THRESH.value <= 32'h0;
        end else begin
            if(field_combo.CD_SPEED_THRESH.THRESH.load_next) begin
                field_storage.CD_SPEED_THRESH.THRESH.value <= field_combo.CD_SPEED_THRESH.THRESH.next;
            end
        end
    end
    assign hwif_out.CD_SPEED_THRESH.THRESH.value = field_storage.CD_SPEED_THRESH.THRESH.value;
    // Field: registers.CD_NON_FATAL_ACCEL_THRESH.THRESH
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CD_NON_FATAL_ACCEL_THRESH.THRESH.value;
        load_next_c = '0;
        if(decoded_reg_strb.CD_NON_FATAL_ACCEL_THRESH && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CD_NON_FATAL_ACCEL_THRESH.THRESH.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CD_NON_FATAL_ACCEL_THRESH.THRESH.next = next_c;
        field_combo.CD_NON_FATAL_ACCEL_THRESH.THRESH.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.CD_NON_FATAL_ACCEL_THRESH.THRESH.value <= 32'h7d;
        end else begin
            if(field_combo.CD_NON_FATAL_ACCEL_THRESH.THRESH.load_next) begin
                field_storage.CD_NON_FATAL_ACCEL_THRESH.THRESH.value <= field_combo.CD_NON_FATAL_ACCEL_THRESH.THRESH.next;
            end
        end
    end
    assign hwif_out.CD_NON_FATAL_ACCEL_THRESH.THRESH.value = field_storage.CD_NON_FATAL_ACCEL_THRESH.THRESH.value;
    // Field: registers.CD_FATAL_ACCEL_THRESH.THRESH
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CD_FATAL_ACCEL_THRESH.THRESH.value;
        load_next_c = '0;
        if(decoded_reg_strb.CD_FATAL_ACCEL_THRESH && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CD_FATAL_ACCEL_THRESH.THRESH.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CD_FATAL_ACCEL_THRESH.THRESH.next = next_c;
        field_combo.CD_FATAL_ACCEL_THRESH.THRESH.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.CD_FATAL_ACCEL_THRESH.THRESH.value <= 32'h7d;
        end else begin
            if(field_combo.CD_FATAL_ACCEL_THRESH.THRESH.load_next) begin
                field_storage.CD_FATAL_ACCEL_THRESH.THRESH.value <= field_combo.CD_FATAL_ACCEL_THRESH.THRESH.next;
            end
        end
    end
    assign hwif_out.CD_FATAL_ACCEL_THRESH.THRESH.value = field_storage.CD_FATAL_ACCEL_THRESH.THRESH.value;
    // Field: registers.CD_ANGULAR_SPEED_THRESH.THRESH
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CD_ANGULAR_SPEED_THRESH.THRESH.value;
        load_next_c = '0;
        if(decoded_reg_strb.CD_ANGULAR_SPEED_THRESH && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CD_ANGULAR_SPEED_THRESH.THRESH.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.CD_ANGULAR_SPEED_THRESH.THRESH.next = next_c;
        field_combo.CD_ANGULAR_SPEED_THRESH.THRESH.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.CD_ANGULAR_SPEED_THRESH.THRESH.value <= 32'h1f40;
        end else begin
            if(field_combo.CD_ANGULAR_SPEED_THRESH.THRESH.load_next) begin
                field_storage.CD_ANGULAR_SPEED_THRESH.THRESH.value <= field_combo.CD_ANGULAR_SPEED_THRESH.THRESH.next;
            end
        end
    end
    assign hwif_out.CD_ANGULAR_SPEED_THRESH.THRESH.value = field_storage.CD_ANGULAR_SPEED_THRESH.THRESH.value;
    // Field: registers.CD_EN.EN
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CD_EN.EN.value;
        load_next_c = '0;
        if(decoded_reg_strb.CD_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CD_EN.EN.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.CD_EN.EN.next = next_c;
        field_combo.CD_EN.EN.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.CD_EN.EN.value <= 1'h0;
        end else begin
            if(field_combo.CD_EN.EN.load_next) begin
                field_storage.CD_EN.EN.value <= field_combo.CD_EN.EN.next;
            end
        end
    end
    assign hwif_out.CD_EN.EN.value = field_storage.CD_EN.EN.value;
    // Field: registers.CD_EN.RESERVED
    always_comb begin
        automatic logic [30:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CD_EN.RESERVED.value;
        load_next_c = '0;
        if(decoded_reg_strb.CD_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CD_EN.RESERVED.value & ~decoded_wr_biten[31:1]) | (decoded_wr_data[31:1] & decoded_wr_biten[31:1]);
            load_next_c = '1;
        end
        field_combo.CD_EN.RESERVED.next = next_c;
        field_combo.CD_EN.RESERVED.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.CD_EN.RESERVED.value <= 31'h0;
        end else begin
            if(field_combo.CD_EN.RESERVED.load_next) begin
                field_storage.CD_EN.RESERVED.value <= field_combo.CD_EN.RESERVED.next;
            end
        end
    end
    assign hwif_out.CD_EN.RESERVED.value = field_storage.CD_EN.RESERVED.value;
    // Field: registers.CD_STATE_RST.RST
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CD_STATE_RST.RST.value;
        load_next_c = '0;
        if(decoded_reg_strb.CD_STATE_RST && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CD_STATE_RST.RST.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.CD_STATE_RST.RST.next = next_c;
        field_combo.CD_STATE_RST.RST.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.CD_STATE_RST.RST.value <= 1'h0;
        end else begin
            if(field_combo.CD_STATE_RST.RST.load_next) begin
                field_storage.CD_STATE_RST.RST.value <= field_combo.CD_STATE_RST.RST.next;
            end
        end
    end
    assign hwif_out.CD_STATE_RST.RST.value = field_storage.CD_STATE_RST.RST.value;
    // Field: registers.CD_STATE_RST.RESERVED
    always_comb begin
        automatic logic [30:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CD_STATE_RST.RESERVED.value;
        load_next_c = '0;
        if(decoded_reg_strb.CD_STATE_RST && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CD_STATE_RST.RESERVED.value & ~decoded_wr_biten[31:1]) | (decoded_wr_data[31:1] & decoded_wr_biten[31:1]);
            load_next_c = '1;
        end
        field_combo.CD_STATE_RST.RESERVED.next = next_c;
        field_combo.CD_STATE_RST.RESERVED.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.CD_STATE_RST.RESERVED.value <= 31'h0;
        end else begin
            if(field_combo.CD_STATE_RST.RESERVED.load_next) begin
                field_storage.CD_STATE_RST.RESERVED.value <= field_combo.CD_STATE_RST.RESERVED.next;
            end
        end
    end
    assign hwif_out.CD_STATE_RST.RESERVED.value = field_storage.CD_STATE_RST.RESERVED.value;
    // Field: registers.POLLING_EN.EN
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.POLLING_EN.EN.value;
        load_next_c = '0;
        if(decoded_reg_strb.POLLING_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.POLLING_EN.EN.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.POLLING_EN.EN.next = next_c;
        field_combo.POLLING_EN.EN.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.POLLING_EN.EN.value <= 1'h0;
        end else begin
            if(field_combo.POLLING_EN.EN.load_next) begin
                field_storage.POLLING_EN.EN.value <= field_combo.POLLING_EN.EN.next;
            end
        end
    end
    assign hwif_out.POLLING_EN.EN.value = field_storage.POLLING_EN.EN.value;
    // Field: registers.POLLING_EN.RESERVED
    always_comb begin
        automatic logic [30:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.POLLING_EN.RESERVED.value;
        load_next_c = '0;
        if(decoded_reg_strb.POLLING_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.POLLING_EN.RESERVED.value & ~decoded_wr_biten[31:1]) | (decoded_wr_data[31:1] & decoded_wr_biten[31:1]);
            load_next_c = '1;
        end
        field_combo.POLLING_EN.RESERVED.next = next_c;
        field_combo.POLLING_EN.RESERVED.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.POLLING_EN.RESERVED.value <= 31'h0;
        end else begin
            if(field_combo.POLLING_EN.RESERVED.load_next) begin
                field_storage.POLLING_EN.RESERVED.value <= field_combo.POLLING_EN.RESERVED.next;
            end
        end
    end
    assign hwif_out.POLLING_EN.RESERVED.value = field_storage.POLLING_EN.RESERVED.value;
    // Field: registers.DATA_PACAKGER_EN.EN
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.DATA_PACAKGER_EN.EN.value;
        load_next_c = '0;
        if(decoded_reg_strb.DATA_PACAKGER_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.DATA_PACAKGER_EN.EN.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.DATA_PACAKGER_EN.EN.next = next_c;
        field_combo.DATA_PACAKGER_EN.EN.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.DATA_PACAKGER_EN.EN.value <= 1'h0;
        end else begin
            if(field_combo.DATA_PACAKGER_EN.EN.load_next) begin
                field_storage.DATA_PACAKGER_EN.EN.value <= field_combo.DATA_PACAKGER_EN.EN.next;
            end
        end
    end
    assign hwif_out.DATA_PACAKGER_EN.EN.value = field_storage.DATA_PACAKGER_EN.EN.value;
    // Field: registers.DATA_PACAKGER_EN.RESERVED
    always_comb begin
        automatic logic [30:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.DATA_PACAKGER_EN.RESERVED.value;
        load_next_c = '0;
        if(decoded_reg_strb.DATA_PACAKGER_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.DATA_PACAKGER_EN.RESERVED.value & ~decoded_wr_biten[31:1]) | (decoded_wr_data[31:1] & decoded_wr_biten[31:1]);
            load_next_c = '1;
        end
        field_combo.DATA_PACAKGER_EN.RESERVED.next = next_c;
        field_combo.DATA_PACAKGER_EN.RESERVED.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.DATA_PACAKGER_EN.RESERVED.value <= 31'h0;
        end else begin
            if(field_combo.DATA_PACAKGER_EN.RESERVED.load_next) begin
                field_storage.DATA_PACAKGER_EN.RESERVED.value <= field_combo.DATA_PACAKGER_EN.RESERVED.next;
            end
        end
    end
    assign hwif_out.DATA_PACAKGER_EN.RESERVED.value = field_storage.DATA_PACAKGER_EN.RESERVED.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [31:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 32'h0) begin
            readback_data_var[10:0] = hwif_in.WRITE_PTR.WPTR.next;
            readback_data_var[31:11] = field_storage.WRITE_PTR.RESERVED.value;
        end
        if(rd_mux_addr == 32'h4) begin
            readback_data_var[10:0] = field_storage.READ_PTR.RPTR.value;
            readback_data_var[31:11] = field_storage.READ_PTR.RESERVED.value;
        end
        if(rd_mux_addr == 32'h8) begin
            readback_data_var[0] = hwif_in.STATUS.EMPTY.next;
            readback_data_var[1] = hwif_in.STATUS.FULL.next;
            readback_data_var[31:2] = field_storage.STATUS.RESERVED.value;
        end
        if(rd_mux_addr == 32'hc) begin
            readback_data_var[31:0] = field_storage.CD_SPEED_THRESH.THRESH.value;
        end
        if(rd_mux_addr == 32'h10) begin
            readback_data_var[31:0] = field_storage.CD_NON_FATAL_ACCEL_THRESH.THRESH.value;
        end
        if(rd_mux_addr == 32'h14) begin
            readback_data_var[31:0] = field_storage.CD_FATAL_ACCEL_THRESH.THRESH.value;
        end
        if(rd_mux_addr == 32'h18) begin
            readback_data_var[31:0] = field_storage.CD_ANGULAR_SPEED_THRESH.THRESH.value;
        end
        if(rd_mux_addr == 32'h1c) begin
            readback_data_var[0] = field_storage.CD_EN.EN.value;
            readback_data_var[31:1] = field_storage.CD_EN.RESERVED.value;
        end
        if(rd_mux_addr == 32'h20) begin
            readback_data_var[0] = field_storage.CD_STATE_RST.RST.value;
            readback_data_var[31:1] = field_storage.CD_STATE_RST.RESERVED.value;
        end
        if(rd_mux_addr == 32'h24) begin
            readback_data_var[0] = field_storage.POLLING_EN.EN.value;
            readback_data_var[31:1] = field_storage.POLLING_EN.RESERVED.value;
        end
        if(rd_mux_addr == 32'h28) begin
            readback_data_var[0] = field_storage.DATA_PACAKGER_EN.EN.value;
            readback_data_var[31:1] = field_storage.DATA_PACAKGER_EN.RESERVED.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
